Repository dotnet/linker, pull requests merged in 2021-09, with the labels that each got.

#2252 Tag analyzer diagnostics as non configurable
  src/ILLink.RoslynAnalyzer/DiagnosticDescriptors.cs
Labels: area-Analyzers

#2250 Update edited document before continuing code fixing
  src/ILLink.CodeFix/BaseAttributeCodeFixProvider.cs
  src/ILLink.CodeFix/RequiresAssemblyFilesCodeFixProvider.cs
  src/ILLink.CodeFix/RequiresUnreferencedCodeCodeFixProvider.cs
  src/ILLink.CodeFix/UnconditionalSuppressMessageCodeFixProvider.cs
  test/ILLink.RoslynAnalyzer.Tests/RequiresAssemblyFilesAnalyzerTests.cs
  test/ILLink.RoslynAnalyzer.Tests/RequiresUnreferencedCodeAnalyzerTests.cs
Labels: area-Analyzers

#2263 Add a test for #2260
  test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NoKeptCtor/OverrideRemoval/Dependencies/OverrideOfAbstractIsKeptNonEmptyLibrary.cs
  test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NoKeptCtor/OverrideRemoval/Dependencies/OverrideOfAbstractIsKeptNonEmptyLibraryWithNonEmpty.cs
  test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NoKeptCtor/OverrideRemoval/OverrideOfAbstractIsKeptNonEmpty.cs
Labels: area-Linker: Tests

#2264 Workaround NRE in SweepStep
  src/linker/Linker.Steps/SweepStep.cs
  test/Mono.Linker.Tests.Cases/Inheritance.AbstractClasses/NoKeptCtor/OverrideRemoval/OverrideOfAbstractIsKeptNonEmpty.cs
Labels: area-Linker: Steps

#2254 Warn on RUC annotated ctors invoked through `new()` constraint in analyzer
  src/ILLink.RoslynAnalyzer/ISymbolExtensions.cs
  src/ILLink.RoslynAnalyzer/RequiresAnalyzerBase.cs
  src/ILLink.RoslynAnalyzer/RequiresUnreferencedCodeAnalyzer.cs
  test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeCapability.cs
Labels: area-Analyzers

#2209 Special case `MakeGenericMethod/Type` in RUC analyzer
  src/ILLink.RoslynAnalyzer/RequiresUnreferencedCodeAnalyzer.cs
  src/ILLink.Shared/DiagnosticId.cs
  src/ILLink.Shared/SharedStrings.resx
  src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
  src/linker/Resources/Strings.Designer.cs
  src/linker/Resources/Strings.resx
  test/ILLink.RoslynAnalyzer.Tests/RequiresUnreferencedCodeAnalyzerTests.cs
Labels: area-Analyzers

#2269 [release/6.0] Update edited document before continuing code fixing
  src/ILLink.CodeFix/BaseAttributeCodeFixProvider.cs
  src/ILLink.CodeFix/RequiresAssemblyFilesCodeFixProvider.cs
  src/ILLink.CodeFix/RequiresUnreferencedCodeCodeFixProvider.cs
  src/ILLink.CodeFix/UnconditionalSuppressMessageCodeFixProvider.cs
  test/ILLink.RoslynAnalyzer.Tests/RequiresAssemblyFilesAnalyzerTests.cs
  test/ILLink.RoslynAnalyzer.Tests/RequiresUnreferencedCodeAnalyzerTests.cs
Labels: area-Analyzers

#2201 Warn on RUC annotated attribute ctors (analyzer)
  src/ILLink.RoslynAnalyzer/RequiresAnalyzerBase.cs
  test/ILLink.RoslynAnalyzer.Tests/LinkerTestCases.cs
  test/ILLink.RoslynAnalyzer.Tests/TestCaseUtils.cs
  test/ILLink.RoslynAnalyzer.Tests/TestChecker.cs
  test/ILLink.RoslynAnalyzer.Tests/Verifiers/CSharpAnalyzerVerifier`1.cs
  test/Mono.Linker.Tests.Cases.Expectations/Assertions/ExpectedWarningAttribute.cs
  test/Mono.Linker.Tests.Cases.Expectations/Assertions/ProducedBy.cs
  test/Mono.Linker.Tests.Cases/RequiresCapability/Dependencies/RequiresUnreferencedCodeOnAttributeCtorAttribute.cs
  test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeCapability.cs
  test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeInCompilerGeneratedCode.cs
  test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresUnreferencedCodeOnAttributeCtor.cs
  test/Mono.Linker.Tests/TestCasesRunner/ResultChecker.cs
Labels: area-Analyzers

#2184 Add DynamicallyAccessedMembers analyzer
  src/ILLink.RoslynAnalyzer/DynamicallyAccessedMemberTypes.cs
  src/ILLink.RoslynAnalyzer/DynamicallyAccessedMembersAnalyzer.cs
  src/ILLink.RoslynAnalyzer/ISymbolExtensions.cs
  src/ILLink.RoslynAnalyzer/RequiresAnalyzerBase.cs
  src/ILLink.Shared/Annotations.cs
  src/ILLink.Shared/DiagnosticId.cs
  src/ILLink.Shared/DiagnosticString.cs
  src/ILLink.Shared/ILLink.Shared.projitems
  src/ILLink.Shared/MessageFormat.cs
  src/ILLink.Shared/SharedStrings.resx
  src/linker/Linker.Dataflow/ReflectionMethodBodyScanner.cs
  test/ILLink.RoslynAnalyzer.Tests/DynamicallyAccessedMembersAnalyzerTests.cs
  test/ILLink.RoslynAnalyzer.Tests/Verifiers/CSharpAnalyzerVerifier`1.cs
Labels: area-Analyzers
