Repository dotnet/linker, pull requests merged in 2022-05, with the labels that each got.

#2774 Add ability for the analyzer to recognize const fields
  src/ILLink.RoslynAnalyzer/TrimAnalysis/TrimAnalysisVisitor.cs
  test/Mono.Linker.Tests.Cases/DataFlow/GetTypeDataFlow.cs
Labels: area-Analyzers

#2781 Adds support for recognizing more integer types as consts
  src/ILLink.RoslynAnalyzer/TrimAnalysis/TrimAnalysisVisitor.cs
  test/Mono.Linker.Tests.Cases/DataFlow/ArrayDataFlow.cs
Labels: area-Analyzers

#2788 Match analyzer and linker requires methods
  src/ILLink.RoslynAnalyzer/RequiresAnalyzerBase.cs
  src/ILLink.RoslynAnalyzer/RequiresISymbolExtensions.cs
  src/ILLink.RoslynAnalyzer/RequiresUnreferencedCodeUtils.cs
  src/ILLink.Shared/DiagnosticId.cs
  src/ILLink.Shared/ILLink.Shared.projitems
  src/ILLink.Shared/MessageSubCategory.cs
  src/ILLink.Shared/SharedStrings.resx
  src/linker/Linker.Steps/MarkStep.cs
  src/linker/Linker.Steps/ValidateVirtualMethodAnnotationsStep.cs
  src/linker/Linker/Annotations.cs
  test/Mono.Linker.Tests.Cases/RequiresCapability/RequiresOnStaticConstructor.cs
Labels: area-Analyzers

#2794 Retarget product binaries to .NET 6
  Directory.Build.props
  src/ILLink.Tasks/LinkTask.cs
  src/ILLink.Tasks/build/Microsoft.NET.ILLink.Tasks.props
  test/Directory.Build.props
Labels: Area-Infrastructure

#2804 Better tests for attribute dataflow
  test/Mono.Linker.Tests.Cases/DataFlow/AttributeConstructorDataflow.cs
  test/Mono.Linker.Tests.Cases/DataFlow/AttributeFieldDataflow.cs
  test/Mono.Linker.Tests.Cases/DataFlow/AttributePropertyDataflow.cs
Labels: area-Linker: Tests
